config/routes.rb
Rails.application.routes.draw do
  root 'search#new'
  get 'search/results'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def new
  end

  def results
    result = HTTParty.get("http://api.openweathermap.org/data/2.5/weather?q=#{params[:zipcode]}&units=imperial&appid=#{Figaro.env.open_weather_map_api_key}")

    if result.code == 200
      #conditions
      @name = result['name']
      @description = result['weather'].first['description']
      # first gives you the first object in the the hash - it's just how the weather app has it set up
      @icon = result['weather'].first['icon']
      @temp = result['main']['temp']
      @temp_high = result['main']['temp_max']
      @temp_low = result['main']['temp_min']
      @humidity = result['main']['humidity']
    else
      @error_message = result['message']
    end


  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Weatherdex</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>

  </body>
</html>

app/views/search/_form.html.erb
<div class="container">
  <%= form_tag(search_results_path, method: :get) do %>
    <%= text_field_tag :zipcode, nil, placeholder: 'Enter a Location', autofocus: true %>
    <%= submit_tag 'Get Weather', class: 'btn btn-info' %>
  <% end %>
</div>

app/views/search/new.html.erb
<%= render 'form'

app/views/search/results.html.erb
<div class="well">
  <% if @error_message.nil? %>
      <h1>Currently in <%= @name %></h1>
      <h4>Condition: <%= @description %> <%= image_tag "http://openweathermap.org/img/w/#{@icon}.png" %></h4>
      <h4>Current Temperature: <%= @temp.to_i %>&deg;F</h4>
      <h4>Humidity: <%= @humidity %>&percnt;</h4>
      <h4>High: <%= @temp_high.to_i %>&deg;F</h4>
      <h4>Low: <%= @temp_low.to_i %>&deg;F</h4>
    <% else %>
      <div class="alert alert-danger" role = "alert">
        <%= @error_message %>
      </div>
    <% end %>
</div>

<div class="well">
  <%= render 'form' %>
</div>